### ISSUE TITLE
Overlay Tweaks conflict with Immediately fast a bit

### ISSUE THREAD

**Issue by Quotions** [MicrocontrollersDev/OverlayTweaks#15]
Hello, i contact immediatly fast owner and they told me to contact you.

When Overlay Tweaks and Immediately fast installed, it causes the villagers sleeves & feet to be visible like this one below:
![3](https://github.com/MicrocontrollersDev/OverlayTweaks/assets/131556546/59255057-7c6e-49c2-85c1-601f128493c3)

**To Reproduce:**

1. Install Immediately fast mod and overlay tweaks on version 1.20.4
2. Launch the game and create a new world
3. Summon a villager and see the results

I had to remove overlay tweaks for this ;d

**Comment by MicrocontrollersDev** [comment]
Please check if this still happens with version 1.5.2: https://modrinth.com/mod/overlaytweaks/version/1.5.2

this is was a funny bug and honestly im still not sure why it happens. its because of ridden entity opacity. i had messed up logic and was accidentally setting the render layers for entities translucent when i shouldnt be. fixed my logic and made it better to only work on the entities you can actually change. now it no longer happens to me but i still dont understand the underlying issue (whatever tho less work for me)

**Comment by Quotions** [comment]
Hello, after installing the new update, it now works fine and now i can use both mods.
I didn't expect the issue to be from overlay tweaks at all, i had to remove my mods and test them one by one.
Thank you for the fix

**Comment by MicrocontrollersDev** [comment]
awesome! sorry this happened i got a bit lazy with my code
